name: Tests Actions
run-name: ${{ github.actor }} is running tests 🚀

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true

      - name: Create conda environment
        run: |
          conda env create -f environment.yml
          conda activate made
        shell: bash -l {0}

      - name: Verify conda environment
        run: |
          conda info
          conda list
        shell: bash -l {0}

      - name: Run tests
        woking-directory: project
        run: |
          chmod +x tests.sh
          ./tests.sh
        shell: bash -l {0}

